"""
Email Service — Automated Intelligence Briefing Digest
───────────────────────────────────────────────────────
Generates polished HTML email digests from watchlist topics
and sends them via SMTP.
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime, timezone


def generate_briefing_html(topics_results: list[dict]) -> str:
    """
    Generate a polished HTML email digest from a list of topic results.
    Each item: {topic, analysis, confidence, sentiment, sources}
    """
    now = datetime.now(timezone.utc).strftime("%B %d, %Y")
    items_html = ""

    for item in topics_results:
        topic = item.get("topic", "Unknown")
        analysis = item.get("analysis", "No analysis available.")
        confidence = item.get("confidence", 0)
        sentiment = item.get("sentiment", "neutral")
        source_count = len(item.get("sources", []))

        # Sentiment color
        s_color = {"positive": "#10b981", "negative": "#ef4444", "mixed": "#f59e0b"}.get(
            sentiment, "#64748b"
        )

        # Top 3 sources
        source_links = ""
        for src in item.get("sources", [])[:3]:
            title = src.get("title", "Source")[:60]
            url = src.get("url", "#")
            source_links += f'<a href="{url}" style="color:#6366f1;text-decoration:none;font-size:13px;">→ {title}</a><br/>'

        items_html += f"""
        <div style="background:#1e293b;border-radius:12px;padding:24px;margin-bottom:20px;border:1px solid #334155;">
            <h2 style="color:#e2e8f0;margin:0 0 8px 0;font-size:18px;">{topic}</h2>
            <div style="display:flex;gap:16px;margin-bottom:12px;">
                <span style="background:#0f172a;color:#60a5fa;padding:4px 10px;border-radius:6px;font-size:12px;">
                    🎯 {confidence}% confidence
                </span>
                <span style="background:#0f172a;color:{s_color};padding:4px 10px;border-radius:6px;font-size:12px;">
                    {sentiment.upper()}
                </span>
                <span style="background:#0f172a;color:#94a3b8;padding:4px 10px;border-radius:6px;font-size:12px;">
                    📰 {source_count} sources
                </span>
            </div>
            <p style="color:#cbd5e1;font-size:14px;line-height:1.6;margin:0 0 12px 0;">
                {analysis[:600]}{'...' if len(analysis) > 600 else ''}
            </p>
            <div style="border-top:1px solid #334155;padding-top:10px;margin-top:10px;">
                {source_links}
            </div>
        </div>
        """

    html = f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"/></head>
<body style="margin:0;padding:0;background:#0f172a;font-family:'Segoe UI',Arial,sans-serif;">
    <div style="max-width:640px;margin:0 auto;padding:32px 20px;">

        <!-- Header -->
        <div style="text-align:center;margin-bottom:32px;">
            <h1 style="color:#6366f1;margin:0;font-size:28px;">⚡ NeuralPulse</h1>
            <p style="color:#64748b;margin:4px 0 0 0;font-size:14px;">Daily Intelligence Briefing — {now}</p>
        </div>

        <!-- Topics -->
        {items_html}

        <!-- Footer -->
        <div style="text-align:center;margin-top:32px;padding-top:20px;border-top:1px solid #1e293b;">
            <p style="color:#475569;font-size:12px;margin:0;">
                Generated by NeuralPulse AI News Intelligence System<br/>
                Powered by Tavily · Groq · Google Gemini
            </p>
        </div>

    </div>
</body>
</html>"""
    return html


def send_briefing(
    to_email: str,
    html_content: str,
    smtp_host: str = "smtp.gmail.com",
    smtp_port: int = 587,
    sender_email: str = "",
    sender_password: str = "",
) -> dict:
    """Send the briefing email via SMTP. Returns status dict."""
    if not sender_email or not sender_password:
        return {"success": False, "error": "SMTP credentials not configured"}

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"⚡ NeuralPulse Daily Briefing — {datetime.now(timezone.utc).strftime('%b %d, %Y')}"
        msg["From"] = sender_email
        msg["To"] = to_email

        # Plain text fallback
        plain = "Your NeuralPulse daily briefing is ready. View it in an HTML-compatible email client."
        msg.attach(MIMEText(plain, "plain"))
        msg.attach(MIMEText(html_content, "html"))

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.send_message(msg)

        return {"success": True, "message": f"Briefing sent to {to_email}"}
    except Exception as e:
        return {"success": False, "error": str(e)}
