"""
PDF Service — Professional Report Generator
─────────────────────────────────────────────
Generates branded NeuralPulse intelligence reports as PDF files.
Uses fpdf2 for server-side generation.
"""

import io
import re
from fpdf import FPDF


class NeuralPulsePDF(FPDF):
    """Custom PDF with NeuralPulse branding."""

    def header(self):
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(99, 102, 241)  # Indigo
        self.cell(0, 12, "NeuralPulse", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(148, 163, 184)
        self.cell(0, 5, "AI News Intelligence Report", new_x="LMARGIN", new_y="NEXT")
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}  |  Generated by NeuralPulse AI", align="C")


def _strip_markdown(text: str) -> str:
    """Remove common markdown formatting for PDF rendering."""
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = re.sub(r"\*(.*?)\*", r"\1", text)
    text = re.sub(r"#{1,6}\s+", "", text)
    text = re.sub(r"\[(.*?)\]\(.*?\)", r"\1", text)
    text = re.sub(r"`(.*?)`", r"\1", text)
    return text


def generate_report_pdf(search_data: dict) -> bytes:
    """
    Generate a professional PDF report from a search result dict.
    Returns raw PDF bytes.
    """
    pdf = NeuralPulsePDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── Title Section ──
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 41, 59)
    query = search_data.get("query", "Unknown Query")
    pdf.multi_cell(0, 8, f"Query: {query}")
    pdf.ln(2)

    # ── Date ──
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 116, 139)
    created = search_data.get("created_at", "N/A")
    pdf.cell(0, 6, f"Generated: {created}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Metrics Row ──
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(60, 8, f"Confidence: {search_data.get('confidence', 0)}%")
    pdf.cell(60, 8, f"Sentiment: {search_data.get('sentiment', 'neutral').title()}")
    pdf.cell(60, 8, f"Bias: {search_data.get('bias', 'center').title()}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    sentiment_score = search_data.get("sentiment_score", 50)
    bias_score = search_data.get("bias_score", 0)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(60, 6, f"Score: {sentiment_score}/100")
    pdf.cell(60, 6, f"Score: {sentiment_score}/100")
    pdf.cell(60, 6, f"Score: {bias_score}/100", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # ── Divider ──
    pdf.set_draw_color(226, 232, 240)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # ── Analysis ──
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 8, "Analysis", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(51, 65, 85)
    analysis = _strip_markdown(search_data.get("result_summary", search_data.get("analysis", "No analysis available.")))
    pdf.multi_cell(0, 5.5, analysis)
    pdf.ln(4)

    # ── Gemini Analysis ──
    gemini = search_data.get("gemini_analysis", "")
    if gemini and gemini != "":
        pdf.set_draw_color(226, 232, 240)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(6)

        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 8, "Gemini Cross-Verification", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(51, 65, 85)
        pdf.multi_cell(0, 5.5, _strip_markdown(gemini))
        pdf.ln(4)

    # ── Entities ──
    entities = search_data.get("entities", [])
    if entities:
        pdf.set_draw_color(226, 232, 240)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(6)

        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 8, "Key Entities", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        pdf.set_font("Helvetica", "", 9)
        for ent in entities[:15]:
            name = ent.get("name", "Unknown")
            etype = ent.get("type", "")
            role = ent.get("role", "")
            pdf.set_text_color(99, 102, 241)
            pdf.cell(50, 5.5, f"  {name}")
            pdf.set_text_color(100, 116, 139)
            pdf.cell(30, 5.5, f"[{etype}]")
            pdf.cell(0, 5.5, role, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    # ── Sources ──
    sources = search_data.get("sources", [])
    if sources:
        pdf.set_draw_color(226, 232, 240)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(6)

        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 8, f"Sources ({len(sources)})", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        pdf.set_font("Helvetica", "", 9)
        for i, src in enumerate(sources[:12], 1):
            title = src.get("title", "Untitled")
            url = src.get("url", "")
            score = src.get("score", 0)
            pdf.set_text_color(30, 41, 59)
            pdf.cell(0, 5.5, f"  {i}. {title[:80]} (relevance: {score:.1%})", new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(100, 116, 139)
            pdf.cell(0, 4.5, f"     {url[:90]}", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)

    # Output
    return pdf.output()
